variables:
  - name: working-dir
    value: 'time_buddy_client/'

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'time_buddy_client/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Hello from 'time_buddy_client'"

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: yarn install
  workingDirectory: $(working-dir)

- script: yarn lint 
  workingDirectory: $(working-dir)

- script: yarn build
  workingDirectory: $(working-dir)