# Generated by Django 4.1 on 2022-10-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_buddy_groups', '0002_rename_organisation_id_organisation_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='id',
            new_name='organisation_id',
        ),
    ]
