# Generated by Django 4.1.2 on 2022-10-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_buddy_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='attendance', to='time_buddy_events.user'),
        ),
        migrations.DeleteModel(
            name='Event_Attendance',
        ),
    ]
