# Generated by Django 4.1 on 2022-08-31 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_buddy_events', '0002_rename_tz_id_event_tz_rename_user_id_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tz',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='time_buddy_events.time_zone'),
        ),
    ]
