# Generated by Django 4.1 on 2022-10-23 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_buddy_events', '0002_event_attendees_delete_event_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='Attendance', to='time_buddy_events.user'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attending', models.BooleanField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_buddy_events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_buddy_events.user')),
            ],
        ),
    ]
