# Generated by Django 4.1 on 2022-10-23 02:55

from django.db import migrations

def create_through_relations(apps, schema_editor):
    Event = apps.get_model('time_buddy_events.Event')
    Attendance = apps.get_model('time_buddy_events.Attendance')
    for event in Event.objects.all():
        for user in Attendance.objects.all():
            Attendance(
                user=user,
                event=event,
                is_attending=False
            ).save()
    
    
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('time_buddy_events', '0003_alter_event_attendees_attendance'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
