# Generated by Django 4.1 on 2022-10-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_buddy_events', '0004_auto_20221023_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
