# Generated by Django 4.1 on 2022-10-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_buddy_events', '0005_remove_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='Attendance', through='time_buddy_events.Attendance', to='time_buddy_events.user'),
        ),
    ]
