# Generated by Django 4.1 on 2022-10-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_buddy_events', '0006_event_attendees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['event']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('user', 'event')},
        ),
    ]
