# Generated by Django 4.1 on 2022-09-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_buddy_support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='answer',
            field=models.CharField(default='test', max_length=512),
            preserve_default=False,
        ),
    ]
