trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'time_buddy_client/*'

jobs:
- job: Test
  displayName: Test Client App

  pool:
    vmImage: ubuntu-latest

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: yarn install
    workingDirectory: $(working-dir)

  - script: yarn lint 
    workingDirectory: $(working-dir)
